name: pokemon_app # Asegúrate de que este sea el nombre de tu proyecto
descrip62_testtion: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Asegúrate de que tu SDK de Flutter sea compatible

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias para la comunicación HTTP y gestión de estado
  http: ^1.2.1 # Para hacer peticiones HTTP
  riverpod: ^2.5.1 # Core de Riverpod
  flutter_riverpod: ^2.5.1 # Integración de Riverpod con Flutter

  # Si decidiste usar freezed/json_serializable para tus modelos (opcional, pero recomendado)
  # freezed_annotation: ^2.4.1
  # json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Si decidiste usar freezed/json_serializable para tus modelos (opcional, pero recomendado)
  # build_runner: ^2.4.9
  # freezed: ^2.4.7
  # json_serializable: ^6.7.1

flutter:
  uses-material-design: true